//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSON_Intellisense.Bower.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSON_Intellisense.Bower.Resources.text", typeof(text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages found matching &apos;{0}&apos;.
        /// </summary>
        internal static string CompletionNoPackageFound {
            get {
                return ResourceManager.GetString("CompletionNoPackageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving version number from Bower....
        /// </summary>
        internal static string CompletionRetrievingVersion {
            get {
                return ResourceManager.GetString("CompletionRetrievingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrive the version number.
        /// </summary>
        internal static string CompletionRetrievingVersionError {
            get {
                return ResourceManager.GetString("CompletionRetrievingVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Bower....
        /// </summary>
        internal static string CompletionSearch {
            get {
                return ResourceManager.GetString("CompletionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently latest version of the package.
        /// </summary>
        internal static string CompletionVersionLatest {
            get {
                return ResourceManager.GetString("CompletionVersionLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches the most recent major version (1.x.x).
        /// </summary>
        internal static string CompletionVersionMajor {
            get {
                return ResourceManager.GetString("CompletionVersionMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches the most recent minor version (1.2.x).
        /// </summary>
        internal static string CompletionVersionMinor {
            get {
                return ResourceManager.GetString("CompletionVersionMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        internal static string QuickInfoHits {
            get {
                return ResourceManager.GetString("QuickInfoHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install package.
        /// </summary>
        internal static string SmartTagInstallPackage {
            get {
                return ResourceManager.GetString("SmartTagInstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open homepage in browser.
        /// </summary>
        internal static string SmartTagNavigateToHomepage {
            get {
                return ResourceManager.GetString("SmartTagNavigateToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package&apos;s doesn&apos;t specify a valid homepage.
        /// </summary>
        internal static string SmartTagNavigateToHomepageError {
            get {
                return ResourceManager.GetString("SmartTagNavigateToHomepageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall package.
        /// </summary>
        internal static string SmartTagUninstallPackage {
            get {
                return ResourceManager.GetString("SmartTagUninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update package.
        /// </summary>
        internal static string SmartTagUpdatePackage {
            get {
                return ResourceManager.GetString("SmartTagUpdatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package....
        /// </summary>
        internal static string statusbarInstalling {
            get {
                return ResourceManager.GetString("statusbarInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling pacakge....
        /// </summary>
        internal static string statusbarUninstalling {
            get {
                return ResourceManager.GetString("statusbarUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating package....
        /// </summary>
        internal static string statusbarUpdating {
            get {
                return ResourceManager.GetString("statusbarUpdating", resourceCulture);
            }
        }
    }
}
