//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSON_Intellisense._Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSON_Intellisense._Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle visibility.
        /// </summary>
        internal static string ClickToToggleVisibility {
            get {
                return ResourceManager.GetString("ClickToToggleVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exact version of the package.
        /// </summary>
        internal static string CompletionVersionLatest {
            get {
                return ResourceManager.GetString("CompletionVersionLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent major version.
        /// </summary>
        internal static string CompletionVersionMajor {
            get {
                return ResourceManager.GetString("CompletionVersionMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent minor version.
        /// </summary>
        internal static string CompletionVersionMinor {
            get {
                return ResourceManager.GetString("CompletionVersionMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restoring Bower/npm packages. See output window for details..
        /// </summary>
        internal static string ErrorRestoringPackages {
            get {
                return ResourceManager.GetString("ErrorRestoringPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package restore complete.
        /// </summary>
        internal static string PackageRestoreComplete {
            get {
                return ResourceManager.GetString("PackageRestoreComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Bower package restore....
        /// </summary>
        internal static string RunningBowerRestore {
            get {
                return ResourceManager.GetString("RunningBowerRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running npm package restore....
        /// </summary>
        internal static string RunningNpmRestore {
            get {
                return ResourceManager.GetString("RunningNpmRestore", resourceCulture);
            }
        }
    }
}
